version: "3.1"

services:
  joomla:
    image: joomla:latest
    #container_name: joomla
    hostname: joomla
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
      - 443:443
    volumes:
      - "./public_html/:/var/www/html/"
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: local
      JOOMLA_DB_USER: local
      JOOMLA_DB_NAME: local

  mysql:
    image: mysql:5.7.27
    #container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
